import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/navbar";
import { AuthProvider } from "./_components/utils/context/auth";
import { PopupProvider } from "./_components/utils/context/popup_provider";
import QueryProvider from "./_components/utils/query/query";
import PopupComponent from "./_components/popup/popup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <PopupProvider>
            <QueryProvider>
            <Navbar />
            <PopupComponent />
            {children}
            </QueryProvider>
          </PopupProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
